; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
board_build.partitions = partitions.csv
board_build.filesystem = littlefs
board_build.f_cpu = 240000000L
upload_speed = 921600
lib_deps = 
	gin66/FastAccelStepper@^0.33.0
	milesburton/DallasTemperature@^3.11.0
	paulstoffregen/OneWire@^2.3.8
	bblanchon/ArduinoJson@^7.0.4
	teemuatlut/TMCStepper@^0.7.3
	https://github.com/ESP32Async/ESPAsyncWebServer.git
	https://github.com/ESP32Async/AsyncTCP.git
	WebServer
	throwtheswitch/Unity@2.6.1
	h2zero/NimBLE-Arduino@^2.5.0
lib_ldf_mode = deep
build_flags = 
	-DCORE_DEBUG_LEVEL=3
	-DBUFFER_SIZE=1024
	-Wall
	-Wextra
	-Wno-unused-parameter
	-Wno-error
	-std=c++17
board_build.esp-idf.sdkconfig = sdkconfig
check_tool = clangtidy
check_flags = clangtidy: --checks=-*,bugprone-*,modernize-*,readability-*,-readability-magic-numbers,-readability-identifier-length,-readability-make-member-function-const,-modernize-use-trailing-return-type,-modernize-redundant-void-arg
check_skip_packages = yes
